### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by kbarbora** [saikat107/Devign#2]
Hi, I came across to your code and thank you for open sourcing.

I was reading your code and I was wondering which dataset are you using?
Are you using the raw dataset provided by the authors?
or did you use Joern to pre-process it?
Can you share the dataset so I can test your code?

Thank you.

**Comment by saikat107** [comment]
Please follow the steps [here](https://github.com/saikat107/Devign/blob/master/README.md#usage)
